# Generated by Django 3.0.3 on 2020-03-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0002_prpm_v_grt_project_eis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRPM_v_grt_pj_team_eis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('user_real_name_th', models.CharField(max_length=300)),
                ('user_last_name_th', models.CharField(max_length=300)),
            ],
        ),
    ]
