# Generated by Django 3.0.3 on 2020-03-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0003_prpm_v_grt_pj_team_eis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRPM_v_grt_pj_budget_eis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psu_project_id', models.IntegerField()),
                ('budget_group_desc', models.CharField(max_length=50)),
                ('budget_type_th', models.CharField(max_length=50)),
                ('budget_source_th', models.CharField(max_length=50)),
                ('budget_year', models.IntegerField()),
                ('budget_amount', models.IntegerField()),
            ],
        ),
    ]
