# Generated by Django 3.0.3 on 2020-04-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0004_prpm_v_grt_pj_budget_eis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRPM_scopus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('n_of_publish', models.IntegerField()),
            ],
        ),
    ]
