# Generated by Django 3.0.3 on 2020-04-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0005_prpm_scopus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prpm_scopus',
            name='prpm_scopus_id',
        ),
    ]
