# Generated by Django 3.0.3 on 2020-04-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0006_remove_prpm_scopus_prpm_scopus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prpm_scopus',
            name='save_date',
        ),
    ]
