# Generated by Django 3.0.3 on 2020-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0006_auto_20200407_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_ranking_university_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5)),
                ('name_eng', models.CharField(max_length=300)),
                ('name_th', models.CharField(max_length=300)),
                ('af_id', models.CharField(max_length=100)),
            ],
        ),
    ]
