# Generated by Django 3.0.3 on 2020-07-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0007_master_ranking_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_ranking_university_name',
            name='flag_used',
            field=models.BooleanField(choices=[(True, 'ใช้'), (False, 'ไม่ใช้')], default=True),
        ),
        migrations.AlterField(
            model_name='master_ranking_university_name',
            name='af_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
