# Generated by Django 3.0.3 on 2020-05-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0007_auto_20200407_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRPM_ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sco', models.IntegerField()),
                ('isi', models.IntegerField()),
                ('tci', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PRPM_scopus',
        ),
    ]
