# Generated by Django 3.0.3 on 2020-08-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0008_auto_20200729_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_ranking_university_name',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
