# Generated by Django 3.0.3 on 2020-05-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0008_auto_20200505_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRPM_ranking_cited_isi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cited', models.IntegerField()),
            ],
        ),
    ]
