# Generated by Django 3.0.3 on 2020-08-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0009_master_ranking_university_name_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRMIS_V_AW_FOR_RANKING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAFF_ID', models.CharField(max_length=5)),
                ('FNAME_THAI', models.CharField(max_length=300)),
                ('LNAME_THAI', models.CharField(max_length=300)),
                ('FNAME_ENG', models.CharField(max_length=300)),
                ('LNAME_ENG', models.CharField(max_length=300)),
                ('POS_NAME_THAI', models.CharField(max_length=300)),
                ('TYPE_ID', models.IntegerField()),
                ('CORRESPONDING', models.IntegerField()),
                ('END_YEAR', models.IntegerField()),
                ('JDB_ID', models.IntegerField()),
                ('JDB_NAME', models.CharField(max_length=500)),
                ('AT_PERCENT', models.IntegerField()),
            ],
        ),
    ]
